# -*- coding: utf-8 -*-
"""XGBoost_Regression_Tourist Accommodation Demand Forecasting Model 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183lZrKGDVSKoQ3sJLpIN7i8osFGx87JD

# 🏝️ **Tourist Accommodation Demand Forecasting System (XGBoost)**  

## 📝 **Introduction**  
This system utilizes the **XGBoost (Extreme Gradient Boosting) model** to predict tourist accommodation demand based on multiple factors. By leveraging historical trends, weather conditions, economic indicators, and seasonal patterns, the model aims to provide accurate forecasts to support decision-making in the tourism sector.  

## **🚀 Training and Evaluation**

This XGBoost model undergoes multiple training iterations to optimize its predictions. The performance is evaluated using these forecasting metrics:

* **Mean Absolute Error (MAE)** – Measures average absolute differences between predicted and actual values.

* **Root Mean Squared Error (RMSE)** – Evaluates prediction accuracy by penalizing larger errors.

* **Mean Absolute Percentage Error (MAPE)** – Represents error as a percentage of actual values.

**Install required packages**
"""

# Run once to install: pip install optuna plotly xgboost scikit-learn pandas numpy

"""**Import Libraries**"""

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split, TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import optuna
import warnings
from datetime import datetime
import os
import webbrowser

warnings.filterwarnings('ignore')
optuna.logging.set_verbosity(optuna.logging.WARNING)
pio.renderers.default = 'browser'

"""**Upload and Load Data**"""

CSV_PATH = r"c:\Users\User\Pictures\For XGBoost\2016 - 2025 datasets.csv"
print("\n📁 Loading data from:", CSV_PATH)
df = pd.read_csv(CSV_PATH)

print(f"\n✅ File loaded: {len(df)} rows")
print("\nRaw data (first 5 rows):")
print(df.head())

"""**Data Preprocessing & Cleaning**"""

df['Date'] = pd.to_datetime(df['Year'].astype(str) + ' ' + df['Month'], format='%Y %B')
df.set_index('Date', inplace=True)
df.sort_index(inplace=True)

print(f"\n✅ Date range: {df.index.min().date()} to {df.index.max().date()}")
print(f"✅ Total records: {len(df)} months")
print("\nProcessed data (first 5 rows):")
print(df.head())

"""**Defining Evaluation Function**"""

def evaluate_model(y_true, y_pred, dataset_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    # Handle potential zero values in MAPE
    mask = y_true != 0
    if mask.any():
        mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100
        accuracy = 100 - mape
    else:
        mape = np.inf
        accuracy = 0

    return {
        'mae': mae,
        'rmse': rmse,
        'r2': r2,
        'mape': mape if mape != np.inf else 0,
        'accuracy': accuracy
    }

# Get last date for future predictions
last_date = df.index.max()
future_12m = pd.date_range(start=last_date + pd.DateOffset(months=1), periods=12, freq='MS')

"""# **XGBoost Version 1.0**

**Featured Data Parameters**

**🏖️ Seasonal and Holiday-Based Features**

- **✅ Peak Season** – Indicates whether a given month falls within the peak tourist season in Panglao Bohol.

- **📅 Philippine Holidays** – Considers national holidays that may influence tourist arrivals.

- **🌍 Top 10 Foreign Market Holidays** – Includes holidays from the top 10 countries contributing to Philippine tourism.

**Prepare data for Version 1**
"""

df_v1 = df.copy()

"""**Feature Engineering for Version 1.0**"""

#Time Features
df_v1['Year'] = df_v1.index.year
df_v1['Month_Num'] = df_v1.index.month

# Drop NaN values
df_v1 = df_v1.dropna()

# Features for V1
features_v1 = ['Peak_Season', 'Philippine_Holidays', 'Top10Market_Holidays']
X_v1 = df_v1[features_v1]
y_v1 = df_v1['Arrivals']

"""**Split Data into Training & Testing (80-20 split)**"""

split_point = int(len(X_v1) * 0.8)
X_train_v1, X_test_v1 = X_v1.iloc[:split_point], X_v1.iloc[split_point:]
y_train_v1, y_test_v1 = y_v1.iloc[:split_point], y_v1.iloc[split_point:]

print(f"\nVersion 1.0 Data Split:")
print(f"Training: {X_train_v1.index.min().date()} to {X_train_v1.index.max().date()} ({len(X_train_v1)} months)")
print(f"Testing: {X_test_v1.index.min().date()} to {X_test_v1.index.max().date()} ({len(X_test_v1)} months)")

"""**Train Version 1.0 Model**"""

model_v1 = xgb.XGBRegressor(
    n_estimators=300,
    max_depth=2,
    learning_rate=0.05,
    random_state=42,
    n_jobs=-1
)

model_v1.fit(X_train_v1, y_train_v1)

"""**Predictions on Test Data**"""

y_pred_train_v1 = model_v1.predict(X_train_v1)
y_pred_test_v1 = model_v1.predict(X_test_v1)
y_pred_train_v1_rounded = np.round(y_pred_train_v1).astype(int)
y_pred_test_v1_rounded = np.round(y_pred_test_v1).astype(int)
train_metrics_v1 = evaluate_model(y_train_v1, y_pred_train_v1_rounded, "V1.0 TRAIN")
test_metrics_v1 = evaluate_model(y_test_v1, y_pred_test_v1_rounded, "V1.0 TEST")

print("\nPredicted vs Actual Values:")
print(pd.DataFrame({'Actual': y_test_v1.values, 'Predicted': y_pred_test_v1_rounded}).head(10))

"""**Model Evaluation & Visualization**"""

print("=" * 80)
print("VERSION 1.0: Model Evaluation & Visualization")
print("=" * 80)

# 1.1 TEST PERFORMANCE
print("\n📈 TEST PERFORMANCE:")
print("-" * 40)
print(f"   MAE: {test_metrics_v1['mae']:,.0f} arrivals")
print(f"   RMSE: {test_metrics_v1['rmse']:,.0f} arrivals")
print(f"   MAPE: {test_metrics_v1['mape']:.2f}%")
print(f"   Accuracy: {test_metrics_v1['accuracy']:.2f}%")

# 1.2 TEST SET PREDICTION CHART
print("\n📊 TEST SET PREDICTION CHART:")
print("-" * 40)

fig_v1_test = go.Figure()
fig_v1_test.add_trace(go.Scatter(
    x=X_test_v1.index,
    y=y_test_v1,
    mode='lines+markers',
    name='Actual',
    line=dict(color='blue', width=2),
    marker=dict(size=8, color='blue')
))

# Add predicted values
fig_v1_test.add_trace(go.Scatter(
    x=X_test_v1.index,
    y=y_pred_test_v1_rounded,
    mode='lines+markers',
    name='Predicted',
    line=dict(color='red', width=2, dash='dash'),
    marker=dict(size=8, color='red', symbol='circle')
))

fig_v1_test.update_layout(
    title='V1.0 - Actual vs Predicted Arrivals',
    xaxis_title='Month',
    yaxis_title='Arrivals',
    hovermode='x unified',
    template='plotly_white',
    height=450,
    width=1000,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5)
)
fig_v1_test.update_xaxes(tickformat='%b %Y', tickangle=45)

# 1.3 FUTURE PREDICTIONS
print("\n🔮 FUTURE PREDICTIONS:")
print("-" * 40)

# Create future prediction for V1
future_v1_12m = pd.DataFrame(index=future_12m)
future_v1_12m['Peak_Season'] = future_v1_12m.index.month.isin([8,12]).astype(int)
future_v1_12m['Philippine_Holidays'] = future_v1_12m.index.month.map({1:2,2:1,3:2,4:3,5:2,6:2,7:1,8:2,9:1,10:1,11:3,12:4})
future_v1_12m['Top10Market_Holidays'] = 15

# Make predictions
pred_v1_12m = model_v1.predict(future_v1_12m[features_v1])
pred_v1_12m_rounded = np.round(pred_v1_12m).astype(int)

# Display 12-month predictions with chart
print("\n📅 NEXT 12 MONTHS PREDICTIONS:")
for i, date in enumerate(future_12m):
    print(f"   {date.strftime('%b %Y')}: {pred_v1_12m_rounded[i]:,} arrivals ({pred_v1_12m_rounded[i]/1000:.1f}k)")

# 12-Month Chart
fig_v1_12m = go.Figure()
fig_v1_12m.add_trace(go.Scatter(
    x=future_12m,
    y=pred_v1_12m_rounded,
    mode='lines+markers',
    name='V1.0 Predictions',
    line=dict(color='red', width=3),
    marker=dict(size=6, color='red', symbol='circle')
))
fig_v1_12m.update_layout(
    title='V1.0 - Next 12 Months Predictions',
    xaxis_title='Month',
    yaxis_title='Predicted Arrivals',
    template='plotly_white',
    height=400,
    width=1000
)
fig_v1_12m.update_xaxes(tickformat='%b %Y', tickangle=45)

"""# **XGBoost Version 2.0**

**Featured Data Parameters**

**🏖️ Seasonal and Holiday-Based Features**

- **✅ Peak Season** – Indicates whether a given month falls within the peak tourist season in Panglao Bohol.

- **📅 Philippine Holidays** – Considers national holidays that may influence tourist arrivals.

- **🌍 Top 10 Foreign Market Holidays** – Includes holidays from the top 10 countries contributing to Philippine tourism.

- **🎅 Is December** – Identifies December, a key holiday season affecting travel trends.


**🌦️ Weather-Related Factors in Panglao, Bohol**
- **🌡️ Average High Temperature** – The highest recorded temperature for the month.

- **❄️ Average Low Temperature** – The lowest recorded temperature for the month.

- **☔ Precipitation** – Measures monthly rainfall, which may impact travel decisions.


**📉 Economic Indicator in Bohol, Philippines**

- **📊 Inflation Rate** – Represents the general rise in prices, which may affect travel affordability.

- **🏡 Is Lockdown** – Represents a pandemic or disaster is an emergency public health measure that restricts human mobility, closes non-essential businesses, and mandates that people stay at home to slow the spread of a contagious disease (like COVID-19) or reduce risk during a disaster.

**Prepare data for Version 2**
"""

df_v2 = df.copy()

"""**Feature Engineering for Version 2.0**"""

#Time features
df_v2['Year'] = df_v2.index.year
df_v2['Month_Num'] = df_v2.index.month

# Drop NaN
df_v2 = df_v2.dropna()

# Features for V2
features_v2 = ['Peak_Season', 'Philippine_Holidays', 'Top10Market_Holidays',
               'Avg_HighTemp', 'Avg_LowTemp', 'Precipitation',
               'Inflation_Rate', 'is_December', 'is_Lockdown']

X_v2 = df_v2[features_v2]
y_v2 = df_v2['Arrivals']

"""**Split Data into Training & Testing (80-20 split)**"""

X_train_v2, X_test_v2 = X_v2.iloc[:split_point], X_v2.iloc[split_point:]
y_train_v2, y_test_v2 = y_v2.iloc[:split_point], y_v2.iloc[split_point:]
print(f"\n📊 V2 Data Split:")
print(f"Training: {X_train_v2.index.min().date()} to {X_train_v2.index.max().date()} ({len(X_train_v2)} months)")
print(f"Testing: {X_test_v2.index.min().date()} to {X_test_v2.index.max().date()} ({len(X_test_v2)} months)")

"""**Train Version 2.0 Model**"""

model_v2 = xgb.XGBRegressor(
    n_estimators=300,
    max_depth=2,
    learning_rate=0.05,
    reg_alpha=0.5,
    reg_lambda=1.0,
    random_state=42,
    n_jobs=-1
)

model_v2.fit(X_train_v2, y_train_v2)

"""**Predictions on Test Data**"""

y_pred_train_v2 = model_v2.predict(X_train_v2)
y_pred_test_v2 = model_v2.predict(X_test_v2)
y_pred_train_v2_rounded = np.round(y_pred_train_v2).astype(int)
y_pred_test_v2_rounded = np.round(y_pred_test_v2).astype(int)
train_metrics_v2 = evaluate_model(y_train_v2, y_pred_train_v2_rounded, "V2.0 TRAIN")
test_metrics_v2 = evaluate_model(y_test_v2, y_pred_test_v2_rounded, "V2.0 TEST")

print("\nPredicted vs Actual Values:")
print(pd.DataFrame({'Actual': y_test_v2.values, 'Predicted': y_pred_test_v2_rounded}).head(10))

"""**Model Evaluation & Visualization**"""

print("\n" + "="*80)
print("📊 VERSION 2.0: Model Evaluation & Visualization")
print("="*80)

# 2.1 TEST PERFORMANCE
print("\n📈 TEST PERFORMANCE:")
print("-" * 40)
print(f"   MAE: {test_metrics_v2['mae']:,.0f} arrivals")
print(f"   RMSE: {test_metrics_v2['rmse']:,.0f} arrivals")
print(f"   MAPE: {test_metrics_v2['mape']:.2f}%")
print(f"   Accuracy: {test_metrics_v2['accuracy']:.2f}%")

# 2.2 TEST SET PREDICTION CHART
print("\n📊 TEST SET PREDICTION CHART:")
print("-" * 40)

fig_v2_test = go.Figure()
fig_v2_test.add_trace(go.Scatter(
    x=X_test_v2.index,
    y=y_test_v2,
    mode='lines+markers',
    name='Actual',
    line=dict(color='blue', width=2),
    marker=dict(size=8, color='blue')
))
fig_v2_test.add_trace(go.Scatter(
    x=X_test_v2.index,
    y=y_pred_test_v2_rounded,
    mode='lines+markers',
    name='Predicted',
    line=dict(color='red', width=2, dash='dash'),
    marker=dict(size=8, color='red', symbol='circle')
))
fig_v2_test.update_layout(
    title='V2.0 - Actual vs Predicted Arrivals',
    xaxis_title='Month',
    yaxis_title='Arrivals',
    hovermode='x unified',
    template='plotly_white',
    height=450,
    width=1000,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5)
)
fig_v2_test.update_xaxes(tickformat='%b %Y', tickangle=45)

# 2.3 FUTURE PREDICTIONS
print("\n🔮 FUTURE PREDICTIONS:")
print("-" * 40)

# Weather maps
temp_high_map = {1:29,2:29,3:30,4:31,5:32,6:32,7:32,8:32,9:32,10:31,11:30,12:29}
temp_low_map = {1:25,2:25,3:25,4:26,5:26,6:26,7:26,8:26,9:26,10:26,11:25,12:25}
precip_map = {1:0.7,2:0.5,3:0.4,4:0.3,5:0.4,6:0.7,7:0.9,8:0.8,9:0.9,10:1.0,11:0.9,12:0.7}

# Create future prediction for V2
future_v2_12m = pd.DataFrame(index=future_12m)
future_v2_12m['Peak_Season'] = future_v2_12m.index.month.isin([8,12]).astype(int)
future_v2_12m['Philippine_Holidays'] = future_v2_12m.index.month.map({1:2,2:1,3:2,4:3,5:2,6:2,7:1,8:2,9:1,10:1,11:3,12:4})
future_v2_12m['Top10Market_Holidays'] = 15
future_v2_12m['Avg_HighTemp'] = future_v2_12m.index.month.map(temp_high_map)
future_v2_12m['Avg_LowTemp'] = future_v2_12m.index.month.map(temp_low_map)
future_v2_12m['Precipitation'] = future_v2_12m.index.month.map(precip_map)
future_v2_12m['Inflation_Rate'] = 3.0
future_v2_12m['is_December'] = (future_v2_12m.index.month == 12).astype(int)
future_v2_12m['is_Lockdown'] = 0

# Make predictions
pred_v2_12m = model_v2.predict(future_v2_12m[features_v2])
pred_v2_12m_rounded = np.round(pred_v2_12m).astype(int)

# Display 12-month predictions with chart
print("\n📅 NEXT 12 MONTHS PREDICTIONS:")
for i, date in enumerate(future_12m):
    print(f"   {date.strftime('%b %Y')}: {pred_v2_12m_rounded[i]:,} arrivals ({pred_v2_12m_rounded[i]/1000:.1f}k)")

fig_v2_12m = go.Figure()
fig_v2_12m.add_trace(go.Scatter(
    x=future_12m,
    y=pred_v2_12m_rounded,
    mode='lines+markers',
    name='V2.0 Predictions',
    line=dict(color='red', width=3),
    marker=dict(size=6, color='red', symbol='circle')
))
fig_v2_12m.update_layout(
    title='V2.0 - Next 12 Months Predictions',
    xaxis_title='Month',
    yaxis_title='Predicted Arrivals',
    template='plotly_white',
    height=400,
    width=1000
)
fig_v2_12m.update_xaxes(tickformat='%b %Y', tickangle=45)

"""# **XGBoost Version 3.0**

**Featured Data Parameters**

**🏖️ Seasonal and Holiday-Based Features**

- **✅ Peak Season** – Indicates whether a given month falls within the peak tourist season in Panglao Bohol.

- **📅 Philippine Holidays** – Considers national holidays that may influence tourist arrivals.

- **🌍 Top 10 Foreign Market Holidays** – Includes holidays from the top 10 countries contributing to Philippine tourism.

- 🔄 **Lag_1 & Lag_2** – Past tourism data from one and two periods ago for trend analysis.  

- 📉 **Rolling_Mean_3m** – Three-month rolling average for smoothing fluctuations.  

- **🎅 Is December** – Identifies December, a key holiday season affecting travel trends.


**🌦️ Weather-Related Factors in Panglao Bohol**
- **🌡️ Average High Temperature** – The highest recorded temperature for the month.

- **❄️ Average Low Temperature** – The lowest recorded temperature for the month.

- **☔ Precipitation** – Measures monthly rainfall, which may impact travel decisions.


**📉 Economic Indicator in Bohol, Philippines**

- **📊 Inflation Rate** – Represents the general rise in prices, which may affect travel affordability.

- **🏡 Is Lockdown** – Represents a pandemic or disaster is an emergency public health measure that restricts human mobility, closes non-essential businesses, and mandates that people stay at home to slow the spread of a contagious disease (like COVID-19) or reduce risk during a disaster.

**Prepare data for Version 3.0**
"""

df_v3 = df.copy()

"""**Feature Engineering for Version 3.0**"""

#Lag Features
df_v3['Lag_1'] = df_v3['Arrivals'].shift(1)
df_v3['Lag_2'] = df_v3['Arrivals'].shift(2)
df_v3['Rolling_Mean_3m'] = df_v3['Arrivals'].rolling(window=3, min_periods=1).mean()

# Time Features
df_v3['Year'] = df_v3.index.year
df_v3['Month_Num'] = df_v3.index.month

# Growth Rate
df_v3['Growth_Rate'] = df_v3['Arrivals'].pct_change() * 100
df_v3['Sudden_Increase'] = (df_v3['Growth_Rate'] > df_v3['Growth_Rate'].quantile(0.75)).astype(int)

# Drop NaN from Lag Features
df_v3 = df_v3.dropna()

# Features for V3
features_v3 = ['Peak_Season', 'Philippine_Holidays', 'Top10Market_Holidays',
               'Avg_HighTemp', 'Avg_LowTemp', 'Precipitation',
               'Lag_1', 'Lag_2', 'Rolling_Mean_3m',
               'Year', 'Month_Num', 'Growth_Rate', 'Sudden_Increase',
               'Inflation_Rate', 'is_December', 'is_Lockdown']

X_v3 = df_v3[features_v3]
y_v3 = df_v3['Arrivals']

"""**Split Data into Training & Testing (80-20 split)**"""

X_train_v3, X_test_v3 = X_v3.iloc[:split_point], X_v3.iloc[split_point:]
y_train_v3, y_test_v3 = y_v3.iloc[:split_point], y_v3.iloc[split_point:]

print(f"\n📊 V3 Data Split:")
print(f"Training: {X_train_v3.index.min().date()} to {X_train_v3.index.max().date()} ({len(X_train_v3)} months)")
print(f"Testing: {X_test_v3.index.min().date()} to {X_test_v3.index.max().date()} ({len(X_test_v3)} months)")

"""**Optuna Optimization**"""

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 600, step=50),
        'max_depth': trial.suggest_int('max_depth', 2, 6),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 0.95),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.95),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.1, 2.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.1, 2.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 7),
        'gamma': trial.suggest_float('gamma', 0, 3),
    }

    # Time Series Cross-Validation
    from sklearn.model_selection import TimeSeriesSplit
    tscv = TimeSeriesSplit(n_splits=3)
    cv_scores = []

    for train_idx, val_idx in tscv.split(X_train_v3):
        X_tr = X_train_v3.iloc[train_idx]
        X_val = X_train_v3.iloc[val_idx]
        y_tr = y_train_v3.iloc[train_idx]
        y_val = y_train_v3.iloc[val_idx]

        model = xgb.XGBRegressor(**params, random_state=42, n_jobs=-1)
        model.fit(X_tr, y_tr)
        y_pred = model.predict(X_val)
        cv_scores.append(mean_absolute_error(y_val, y_pred))

    return np.mean(cv_scores)

print("\n🎯 Running Optuna optimization with 100 trials (3-fold Time Series CV)...")
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=100, show_progress_bar=True)

print(f"\nBest CV MAE: {study.best_value:.2f}")
print(f"Best parameters: {study.best_params}")
best_params = study.best_params

"""**Train Version 3.0 Model**"""

model_v3 = xgb.XGBRegressor(**best_params, random_state=42, n_jobs=-1)
model_v3.fit(X_train_v3, y_train_v3)

"""**Predictions on Test Data**"""

y_pred_train_v3 = model_v3.predict(X_train_v3)
y_pred_test_v3 = model_v3.predict(X_test_v3)
y_pred_train_v3_rounded = np.round(y_pred_train_v3).astype(int)
y_pred_test_v3_rounded = np.round(y_pred_test_v3).astype(int)
train_metrics_v3 = evaluate_model(y_train_v3, y_pred_train_v3_rounded, "V3.0 TRAIN")
test_metrics_v3 = evaluate_model(y_test_v3, y_pred_test_v3_rounded, "V3.0 TEST")

print("\nPredicted vs Actual Values:")
print(pd.DataFrame({'Actual': y_test_v3.values, 'Predicted': y_pred_test_v3_rounded}).head(10))

"""**Model Evaluation & Visualization**"""

print("\n" + "="*80)
print("📊 VERSION 3.0: Model Evaluation & Visualization")
print("="*80)

# 3.1 TEST PERFORMANCE
print("\n📈 TEST PERFORMANCE:")
print("-" * 40)
print(f"   MAE: {test_metrics_v3['mae']:,.0f} arrivals")
print(f"   RMSE: {test_metrics_v3['rmse']:,.0f} arrivals")
print(f"   MAPE: {test_metrics_v3['mape']:.2f}%")
print(f"   Accuracy: {test_metrics_v3['accuracy']:.2f}%")

# 3.2 TEST SET PREDICTION CHART
print("\n📊 TEST SET PREDICTION CHART:")
print("-" * 40)

fig_v3_test = go.Figure()
fig_v3_test.add_trace(go.Scatter(
    x=X_test_v3.index,
    y=y_test_v3,
    mode='lines+markers',
    name='Actual',
    line=dict(color='blue', width=2),
    marker=dict(size=8, color='blue')
))
fig_v3_test.add_trace(go.Scatter(
    x=X_test_v3.index,
    y=y_pred_test_v3_rounded,
    mode='lines+markers',
    name='Predicted',
    line=dict(color='red', width=2, dash='dash'),
    marker=dict(size=8, color='red', symbol='circle')
))
fig_v3_test.update_layout(
    title='V3.0 - Actual vs Predicted Arrivals',
    xaxis_title='Month',
    yaxis_title='Arrivals',
    hovermode='x unified',
    template='plotly_white',
    height=450,
    width=1000,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5)
)
fig_v3_test.update_xaxes(tickformat='%b %Y', tickangle=45)

# 3.3 FUTURE PREDICTIONS
print("\n🔮 FUTURE PREDICTIONS:")
print("-" * 40)

# Get last known values for lag features
last_values = df_v3['Arrivals'].values[-3:] if 'df_v3' in dir() else df['Arrivals'].values[-3:]

# Create future prediction for V3
future_v3_12m = pd.DataFrame(index=future_12m)
for df_future in [future_v3_12m]:
    df_future['Peak_Season'] = df_future.index.month.isin([8,12]).astype(int)
    df_future['Philippine_Holidays'] = df_future.index.month.map({1:2,2:1,3:2,4:3,5:2,6:2,7:1,8:2,9:1,10:1,11:3,12:4})
    df_future['Top10Market_Holidays'] = 15
    df_future['Avg_HighTemp'] = df_future.index.month.map(temp_high_map)
    df_future['Avg_LowTemp'] = df_future.index.month.map(temp_low_map)
    df_future['Precipitation'] = df_future.index.month.map(precip_map)
    df_future['Inflation_Rate'] = 3.0
    df_future['is_December'] = (df_future.index.month == 12).astype(int)
    df_future['is_Lockdown'] = 0
    df_future['Year'] = df_future.index.year
    df_future['Month_Num'] = df_future.index.month
    df_future['Lag_1'] = last_values[-1]
    df_future['Lag_2'] = last_values[-2]
    df_future['Rolling_Mean_3m'] = last_values.mean()
    df_future['Growth_Rate'] = ((last_values[-1] - last_values[-2]) / last_values[-2] * 100)
    df_future['Sudden_Increase'] = 0

# Make predictions
pred_v3_12m = model_v3.predict(future_v3_12m[features_v3])
pred_v3_12m_rounded = np.round(pred_v3_12m).astype(int)

# Display 12-month predictions with chart
print("\n📅 NEXT 12 MONTHS PREDICTIONS:")
for i, date in enumerate(future_12m):
    print(f"   {date.strftime('%b %Y')}: {pred_v3_12m_rounded[i]:,} arrivals ({pred_v3_12m_rounded[i]/1000:.1f}k)")

fig_v3_12m = go.Figure()
fig_v3_12m.add_trace(go.Scatter(
    x=future_12m,
    y=pred_v3_12m_rounded,
    mode='lines+markers',
    name='V3.0 Predictions',
    line=dict(color='red', width=3),
    marker=dict(size=6, color='red', symbol='circle')
))
fig_v3_12m.update_layout(
    title='V3.0 - Next 12 Months Predictions',
    xaxis_title='Month',
    yaxis_title='Predicted Arrivals',
    template='plotly_white',
    height=400,
    width=1000
)
fig_v3_12m.update_xaxes(tickformat='%b %Y', tickangle=45)

"""**VERSIONS COMPARISON**"""

print("\n" + "="*80)
print("📊 FINAL SUMMARY - ALL VERSIONS COMPARISON")
print("="*80)

# Test Performance Comparison
print("\n📈 TEST PERFORMANCE COMPARISON:")
print("-" * 60)
print(f"{'Metric':<14} {'V1.0':>10} {'V2.0':>10} {'V3.0':>10}")
print("-" * 60)
print(f"{'MAE':<15} {test_metrics_v1['mae']:>10,.0f} {test_metrics_v2['mae']:>10,.0f} {test_metrics_v3['mae']:>10,.0f}")
print(f"{'RMSE':<15} {test_metrics_v1['rmse']:>10,.0f} {test_metrics_v2['rmse']:>10,.0f} {test_metrics_v3['rmse']:>10,.0f}")
print(f"{'MAPE':<15} {test_metrics_v1['mape']:>9,.2f}% {test_metrics_v2['mape']:>9,.2f}% {test_metrics_v3['mape']:>9,.2f}%")
print(f"{'Accuracy':<15} {test_metrics_v1['accuracy']:>9,.2f}% {test_metrics_v2['accuracy']:>9,.2f}% {test_metrics_v3['accuracy']:>9,.2f}%")

# Future Predictions Comparison (12 Months)
print("\n🔮 FUTURE PREDICTIONS COMPARISON (Next 12 Months):")
print("-" * 70)
print(f"{'Month':<12} {'V1.0':>10} {'V2.0':>10} {'V3.0':>10}")
print("-" * 70)
for i, date in enumerate(future_12m):
    print(f"{date.strftime('%b %Y'):<12} {pred_v1_12m_rounded[i]/1000:>9.1f}k {pred_v2_12m_rounded[i]/1000:>9.1f}k {pred_v3_12m_rounded[i]/1000:>9.1f}k")

# Best Model
print("\n" + "="*80)
accuracies = [test_metrics_v1['accuracy'], test_metrics_v2['accuracy'], test_metrics_v3['accuracy']]
best_idx = accuracies.index(max(accuracies))
best_model = ['V1.0 Baseline', 'V2.0 Weather', 'V3.0 Optimized'][best_idx]
print(f"🏆 BEST MODEL: {best_model} with {max(accuracies):.2f}% accuracy")
print("="*80)

# ============================================================
# COMBINED DASHBOARD — all charts + summary table in one tab
# ============================================================

# Performance comparison table builder
def _row(label, v1, v2, v3, fmt):
    best = min([v1, v2, v3])
    def cell(v):
        style = ' style="background:#d4edda;font-weight:bold"' if v == best else ''
        return f'<td{style}>{fmt.format(v)}</td>'
    return f'<tr><td>{label}</td>{cell(v1)}{cell(v2)}{cell(v3)}</tr>'

perf_table = f"""
<table>
  <thead>
    <tr><th>Metric</th><th>V1.0</th><th>V2.0</th><th>V3.0</th></tr>
  </thead>
  <tbody>
    {_row("MAE",      test_metrics_v1['mae'],  test_metrics_v2['mae'],  test_metrics_v3['mae'],  "{:,.0f}")}
    {_row("RMSE",     test_metrics_v1['rmse'], test_metrics_v2['rmse'], test_metrics_v3['rmse'], "{:,.0f}")}
    {_row("MAPE (%)", test_metrics_v1['mape'], test_metrics_v2['mape'], test_metrics_v3['mape'], "{:.2f}%")}
  </tbody>
</table>"""

acc_best = max(test_metrics_v1['accuracy'], test_metrics_v2['accuracy'], test_metrics_v3['accuracy'])
def _acc_cell(v):
    style = ' style="background:#d4edda;font-weight:bold"' if v == acc_best else ''
    return f'<td{style}>{v:.2f}%</td>'

perf_table = perf_table.replace(
    "</tbody>",
    f'<tr><td>Accuracy (%)</td>'
    f'{_acc_cell(test_metrics_v1["accuracy"])}'
    f'{_acc_cell(test_metrics_v2["accuracy"])}'
    f'{_acc_cell(test_metrics_v3["accuracy"])}'
    f'</tr></tbody>'
)

# 12-month forecast comparison table
forecast_rows = ""
for i, d in enumerate(future_12m):
    forecast_rows += (
        f'<tr><td>{d.strftime("%b %Y")}</td>'
        f'<td>{pred_v1_12m_rounded[i]:,}</td>'
        f'<td>{pred_v2_12m_rounded[i]:,}</td>'
        f'<td>{pred_v3_12m_rounded[i]:,}</td></tr>\n'
    )

forecast_table = f"""
<table>
  <thead>
    <tr><th>Month</th><th>V1.0</th><th>V2.0</th><th>V3.0</th></tr>
  </thead>
  <tbody>
    {forecast_rows}
  </tbody>
</table>"""

# All figures in order
charts = [
    ("V1.0 \u2014 Actual vs Predicted (Test Set)", fig_v1_test),
    ("V1.0 \u2014 Next 12 Months Forecast",        fig_v1_12m),
    ("V2.0 \u2014 Actual vs Predicted (Test Set)", fig_v2_test),
    ("V2.0 \u2014 Next 12 Months Forecast",        fig_v2_12m),
    ("V3.0 \u2014 Actual vs Predicted (Test Set)", fig_v3_test),
    ("V3.0 \u2014 Next 12 Months Forecast",        fig_v3_12m),
]

html_parts = ["""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>XGBoost Tourist Forecasting Dashboard</title>
  <style>
    body  { font-family: Arial, sans-serif; background:#f5f5f5; margin:0; padding:20px; }
    h1    { text-align:center; color:#333; }
    h2    { color:#555; margin-top:40px; border-bottom:2px solid #ddd; padding-bottom:6px; }
    .chart-box, .table-box {
      background:white; border-radius:8px; padding:20px;
      margin-bottom:30px; box-shadow:0 2px 6px rgba(0,0,0,.1);
    }
    table { border-collapse:collapse; width:100%; font-size:14px; }
    th    { background:#4a90d9; color:white; padding:10px 14px; text-align:center; }
    td    { padding:9px 14px; border-bottom:1px solid #eee; text-align:center; }
    tr:hover td { background:#f0f7ff; }
    .badge { display:inline-block; background:#28a745; color:white;
             padding:6px 14px; border-radius:20px; font-size:15px; margin-top:8px; }
  </style>
</head>
<body>
<h1>&#127965;&#65039; XGBoost Tourist Accommodation Demand Forecasting</h1>
"""]

for title, fig in charts:
    fig_html = pio.to_html(fig, full_html=False,
                           include_plotlyjs='cdn' if title == charts[0][0] else False)
    html_parts.append(f'<div class="chart-box"><h2>{title}</h2>{fig_html}</div>\n')

html_parts.append(f"""
<div class="table-box">
  <h2>&#128202; Final Summary \u2014 Test Performance Comparison</h2>
  <p style="font-size:13px;color:#888;">Green highlight = best value per metric.</p>
  {perf_table}
  <p class="badge">&#127942; Best Model: {best_model} &nbsp;({max(accuracies):.2f}% accuracy)</p>
</div>

<div class="table-box">
  <h2>&#128302; Future Predictions Comparison (Next 12 Months)</h2>
  {forecast_table}
</div>
</body></html>
""")

output_path = os.path.join(os.path.dirname(os.path.abspath(CSV_PATH)), "xgboost_dashboard.html")
with open(output_path, "w", encoding="utf-8") as f:
    f.write("".join(html_parts))

print(f"\n\u2705 Dashboard saved to: {output_path}")
webbrowser.open(f"file:///{output_path.replace(os.sep, '/')}")